from fastapi import APIRouter

from app.models.api import AssistLayoutOptions, AssistLayoutRequest, AssistTemplate
from app.services.recommend.orchestrator import plan_assist_templates

router = APIRouter(prefix="/assist", tags=["assist"])


@router.post("/layout", response_model=AssistLayoutOptions)
def assist_layout(req: AssistLayoutRequest) -> AssistLayoutOptions:
    """Propose one or more complete furniture layouts ("templates") for the room.

    Each template is a full, gate-valid layout generated by placing the primary piece
    (sofa/bed) on a different wall - the user picks the one they like and accepts it.
    Deterministic geometry only: products come from the recommendation engine and poses
    from the spatial engine. No LLM/image model decides coordinates.
    """
    templates = plan_assist_templates(
        room=req.room,
        preferences=req.preferences,
        placed_items=req.placed_items,
        categories=req.categories,
        room_type=req.room_type,
    )
    return AssistLayoutOptions(
        templates=[
            AssistTemplate(label=label, recommended=recommended, layout=layout)
            for label, recommended, layout in templates
        ]
    )
